"""new_chagnes_for_multiple_tables

Revision ID: c24e2dcf61ab
Revises: eb58b27a26b6
Create Date: 2025-10-29 20:54:21.785643
"""
from alembic import op
import sqlalchemy as sa

revision = "c24e2dcf61ab"
down_revision = "eb58b27a26b6"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veh_competitor_quotes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicles', ['veh_id'], ['id'])

    with op.batch_alter_table('veh_ext_details', schema=None) as batch_op:
        batch_op.alter_column('fuel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('colour',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('transmission_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'veh_details', ['veh_details_id'], ['id'])

    with op.batch_alter_table('veh_leads', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicles', ['veh_id'], ['id'])

    with op.batch_alter_table('veh_mot_defects', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('veh_mot_details', schema=None) as batch_op:
        batch_op.alter_column('fuelType',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('primaryColour',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'veh_details', ['veh_details_id'], ['id'])

    with op.batch_alter_table('veh_mot_tests', schema=None) as batch_op:
        batch_op.alter_column('odometerUnit',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('veh_rules', schema=None) as batch_op:
        batch_op.alter_column('adjustmentValue',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veh_rules', schema=None) as batch_op:
        batch_op.alter_column('adjustmentValue',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('veh_mot_tests', schema=None) as batch_op:
        batch_op.alter_column('odometerUnit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('veh_mot_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('primaryColour',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('fuelType',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('veh_mot_defects', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('veh_leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('veh_ext_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('transmission_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('colour',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('fuel',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('veh_competitor_quotes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
