"""migration_contact

Revision ID: eb58b27a26b6
Revises: 280937ecfe6c
Create Date: 2025-10-24 11:22:52.691535
"""
from alembic import op
import sqlalchemy as sa

revision = "eb58b27a26b6"
down_revision = "280937ecfe6c"
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veh_contact', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('veh_rules', schema=None) as batch_op:
        batch_op.alter_column('adjustmentValue',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veh_rules', schema=None) as batch_op:
        batch_op.alter_column('adjustmentValue',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('veh_contact', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('lastName',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('firstName',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
